### PR TITLE
GH206: Fix chocolatey nuspec

### LINKED ISSUE #206: Remove all references to CI/CD assets
Looks like there is some copy/pasta at play here...

https://chocolatey.org/packages/clipimg-vscode/0.1.0

image

### PR DESCRIPTION
**Pull request by devlead**
* fixes #206

### CODE REVIEW

**Review by gep13 — APPROVED** [review]
LGTM!

**Comment by gep13** [comment]
@devlead can you rebase this on current develop?

**Comment by devlead** [comment]
> 
> 
> @devlead can you rebase this on current develop?

Done.

**Comment by gep13** [comment]
@devlead your changes have been merged, thanks for your contribution 👍

**Pull request merged**
